### ISSUE TITLE
Where is the TAR model checkpoints?

### ISSUE THREAD

**Issue by boyiwei** [rishub-tamirisa/tamper-resistance#5]
I remember you released the Llama3 checkpoints after TAR in Huggingface a few days ago (https://huggingface.co/lapisrocks/Llama-3-8B-Instruct-TAR-Bio) , but right now it has disappeared. Could you release them again?

**Comment by PinetreePantry** [comment]
I saw these checkpoints are on https://huggingface.co/lapisrocks/Llama-3-8B-Instruct-TAR-Bio again. However, when I download it and prompt it by read-teaming, I found the model seems to behave improperly. Is that the model checkpoint that is tamper resistant?
