### ISSUE TITLE
Request to open-source TAR for harmful request refusal

### ISSUE THREAD

**Issue by haobozhang** [rishub-tamirisa/tamper-resistance#7]
Hi @rishub-tamirisa , I found this repo mainly consists of the code of TAR for weaponization knowledge restriction, but not of the harmful request refusal. Could you please consider open-source the code of harmful request refusal, especially how to use the Harmbench to evaluate your method? I think no details can be found in either this repo or the paper, e.g., are you using all the attacks in Harmbench to evaluate TAR, are you following the original code of Harmbench, the model checkpoint of TAR for harmful request refusal, etc? Thanks!

**Comment by rishub-tamirisa** [comment]
Hi @haobozhang. We include the training code for the harmful request refusal setting; it requires using the `"dpo"` `tamper_resistance_loss_type` from [the TR objective function](https://github.com/rishub-tamirisa/tamper-resistance/blob/main/modules/training.py#L726). 

To train using the DPO tamper-resistance dataloader, you should set the `--subject` flag for the input args in `tar.py` to `dpo_anthropic`, which will use a modified version of the Anthropic-HH-RLHF dataset where rejected completions are replaced with refusals.

We've added the refusal model from the paper to our [HF Model Collection](https://huggingface.co/lapisrocks/Llama-3-8B-Instruct-TAR-Refusal)
